#! /bin/sh

# License: LGPL
# Author: Diego Iastrubni
# $Id$

APPLICATION=demo4.bin

if [ ! -x $APPLICATION ]; then
        echo "You need to first compile the application using the"
	echo "normal \"qmake; make\" commands"

	exit -1
fi

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$PWD

# pass on command line parameters
./$APPLICATION $@


